### ISSUE TITLE
Member edition

### ISSUE THREAD

**Issue by brunodmartins** [brunodmartins/church-members-api#115]
Members data change, thus, this API should support it. 

A new endpoint should exist, allowing data to be modified. Contact, Address and Personal data should each have its own endpoint allowing the modification. 

### Contact interface

`PUT /members/{id}/contact`

Request should follow the current structure `Contact` struct , allowing the cellphone, phone and email to be modified.

### Address interface

`PUT /members/{id}/address`

Request should follow the current structure `Address` struct.

### Person interface

`PUT /members/{id}/person`

Request should allow the following modifications:

- name (first and last)
- birth date
- marriage date + spouses name
- children quantity

**Comment by sagar2395** [comment]
@brunodmartins I would like to work on this

**Comment by brunodmartins** [comment]
@sagar2395 thank you! You can fork and open a PR! One advice: the code is not well prepared for updates now, thus, I would recommend trying to start coding the PUT for contact =)

**Comment by sagar2395** [comment]
Sure, Forked the Repo. Working on this. Kindly assign me the issue
